### ISSUE TITLE
Provide an easier way to disable bundles

### ISSUE THREAD

**Issue by denolfe** [nodecg/nodecg-bundle-parser#1]
_Moved from https://github.com/nodecg/nodecg/issues/124_

When developing a bundle, it would be nice to have a way to easily enable/disable other bundles.

Current workarounds:
- Move bundle to a folder adjacent to `bundles`
- Rename `nodecg.json` to something else ie. `nodecg.json.disabled`
- Add `Enabled` property in `nodecg.json` that is `true` by default but can be flipped to `false`

Ideas:
- Build a command into the nodecg-cli to do one of the above workarounds programmatically

via @thesupremecommander:

> I thought about it a while before, and I think one of the better solutions could be to have a file that NodeCG checks for (something like bundle.disabled). That way, NodeCG doesn't have to parse the entire JSON file just to check if disabled, and enabling/disabling it is as simple as renaming or adding/deleting a file.

**Comment by Lange** [comment]
Resolved https://github.com/nodecg/bundle-manager/pull/19
